import { getLocales } from "expo-localization";
import { PROMPT_IDS } from "@/app/config/promptIds";
import { runPrompt } from "@/app/services/aiClient";
import { parseJsonContent, round1, toNumber } from "@/app/utils/aiJson";
import type {
  MealCategoryEnum,
  MealPhaseKey,
  TranslationMap,
} from "@/app/types/nutrition";

// =====================================================================
// AI weekly meal-plan generator (PromptOT: "ERA Weekly Meal Plan
// Generator"). Each day is generated by its own fast single-day call;
// generateWeeklyMealPlan fires all 7 in PARALLEL via Promise.all and
// flattens them, so total time ≈ slowest single day (not the sum).
// Returns bilingual meals (day_of_week + sort_order) for
// user_meal_plan_items. Region comes from the device locale.
// =====================================================================

const MEALS_PER_DAY_DEFAULT = 4;
const DAYS_IN_WEEK = 7;

export interface WeeklyPlanInput {
  weekNumber: number;
  phase: MealPhaseKey;
  mealsPerDay: number;
  kcal: number;
  protein_g: number;
  carbs_g: number;
  fats_g: number;
}

/** One generated meal, shaped for user_meal_plan_items (no ids yet). */
export interface GeneratedPlanItem {
  day_of_week: number;
  category: MealCategoryEnum;
  sort_order: number;
  name_translations: TranslationMap;
  note_translations: TranslationMap;
  kcal: number;
  protein_g: number;
  carbs_g: number;
  fats_g: number;
}

const ALLOWED_CATEGORIES: MealCategoryEnum[] = [
  "breakfast",
  "lunch",
  "dinner",
  "snack",
];

/** Cuisine region from the device locale's country code. */
const REGION_BY_CODE: Record<string, string> = { IN: "India", NO: "Norway" };

function resolveRegion(): string {
  const code = getLocales()[0]?.regionCode ?? "";
  return REGION_BY_CODE[code] ?? "International (widely available foods)";
}

/**
 * Generate the full week by firing 7 single-day calls in parallel. If any
 * one day fails, Promise.all rejects and the caller (ensureWeekPlan) will
 * surface the error — user can retry from the UI.
 */
export async function generateWeeklyMealPlan(
  input: WeeklyPlanInput,
): Promise<GeneratedPlanItem[]> {
  const sharedVariables = {
    week_number: String(input.weekNumber),
    phase: input.phase,
    region: resolveRegion(),
    meals_per_day: String(input.mealsPerDay || MEALS_PER_DAY_DEFAULT),
    kcal: String(input.kcal),
    protein_g: String(input.protein_g),
    carbs_g: String(input.carbs_g),
    fats_g: String(input.fats_g),
  };

  const dayPromises = Array.from({ length: DAYS_IN_WEEK }, (_, i) => i + 1).map(
    (day) =>
      runPrompt<GeneratedPlanItem[]>({
        promptId: PROMPT_IDS.weeklyMealPlan,
        variables: { ...sharedVariables, day_of_week: String(day) },
        userMessage: `Generate meals for day ${day} of week ${input.weekNumber} (${input.phase} phase).`,
        parse: (content) => parseDayMeals(content, day),
      }),
  );

  const days = await Promise.all(dayPromises);
  return days.flat();
}

// -------- parsing ----------------------------------------------------

/** Parse one day's `{ meals: [...] }` and stamp day_of_week + sort_order. */
function parseDayMeals(content: string, dayOfWeek: number): GeneratedPlanItem[] {
  const parsed = parseJsonContent(content) as { meals?: unknown };
  const rawMeals = Array.isArray(parsed?.meals) ? parsed.meals : [];

  const items: GeneratedPlanItem[] = [];
  rawMeals.forEach((rawMeal, index) => {
    const meal = toMeal(rawMeal, dayOfWeek, index);
    if (meal) items.push(meal);
  });

  if (!items.length) {
    throw new Error(`AI returned no meals for day ${dayOfWeek}.`);
  }
  return items;
}

function toMeal(
  raw: unknown,
  dayOfWeek: number,
  index: number,
): GeneratedPlanItem | null {
  if (!raw || typeof raw !== "object") return null;
  const obj = raw as Record<string, unknown>;

  const name = toTranslationMap(obj.name);
  if (!name.en && !name.nb) return null;

  return {
    day_of_week: dayOfWeek,
    category: toCategory(obj.category),
    sort_order: index,
    name_translations: name,
    note_translations: toTranslationMap(obj.note),
    kcal: Math.round(toNumber(obj.kcal)),
    protein_g: round1(toNumber(obj.protein_g)),
    carbs_g: round1(toNumber(obj.carbs_g)),
    fats_g: round1(toNumber(obj.fats_g)),
  };
}

function toTranslationMap(value: unknown): TranslationMap {
  if (!value || typeof value !== "object") return {};
  const obj = value as Record<string, unknown>;
  const map: TranslationMap = {};
  if (typeof obj.en === "string" && obj.en.trim()) map.en = obj.en.trim();
  if (typeof obj.nb === "string" && obj.nb.trim()) map.nb = obj.nb.trim();
  return map;
}

function toCategory(value: unknown): MealCategoryEnum {
  return ALLOWED_CATEGORIES.includes(value as MealCategoryEnum)
    ? (value as MealCategoryEnum)
    : "snack";
}
